### ISSUE TITLE
Fast Midi Setup

### ISSUE THREAD

**Issue by robinasu** [MrDham/OpenTheremin_V4_with_MIDI#10]
Hello, I would like to use my new Opentheramin with GarageBand. All the serial to MIDI applications for OSX don't seem to work anymore. I noticed a reference to HIDUINO in the pages, here. Is that implemented now, or do I need to add an IC? Maybe I just need to flash the software and enable the midi interface?

**Comment by MrDham** [comment]
Hello, 

I was not active on github recently and didn't receive notification about the issue... Sorry for the very late answer. 

Unfortunatelly Hiduino is not possible without a new IC and related hardware changes : The ship present on the board can't be reprogrammed into a MIDI port on Open Theremin V4.

Adding a new ship being much more complicated than adding a MIDI connector and using a cheap MIDI interface, I'm not sure it is the way to go. 

Vincent
